<?php 
/**
 * Spare functions to extract audio from contents
 */
// qtmplayer_replace_default
function qtmplayer_audio_shortcode( $html, $attr ) {
	if(get_theme_mod( 'qtmplayer_replace_default', '1' ) && !is_admin() ){
		
		ob_start();
		// Post common data:
		$id = get_the_ID();
		$content = get_the_content( $id);
		$tracktitle = get_the_title($id);
		$artist = get_the_author();
		$link = get_the_permalink($id);
		$cover = '';
		$thumb = false;
		if( has_post_thumbnail( $id )) {
			$cover = get_the_post_thumbnail_url(null,array(370,370));
			$thumb = get_the_post_thumbnail_url(null,array(70,70));
		}

		
		// Download or buy
		$buylink =  get_post_meta(  $id, 'qtmplayer_dll', true);
		$ext = pathinfo($buylink, PATHINFO_EXTENSION);
		if( $ext == 'mp3'){
			$buylink = qtmplayer_create_dllink( $buylink );
		}

		
		$track = array();

		// audio shortcode specific data
		if(array_key_exists('mp3', $attr)){
			$file = $attr['mp3'];
		} elseif (array_key_exists(0, $attr)){
			$file = $attr[0];
		}

		/**
		 * Since 1.2.0
		 * Make sure no duplicated block occurs
		 */
		$blocks = parse_blocks( $content );
		$audio = false;
		foreach ($blocks as $block){
			
			if($block['blockName'] == 'core/audio'){
				$audio = $block[ 'innerHTML' ];
				if( $audio ){
					$audio = true;
					return;
				}
			}
		}

		if(!isset( $file ) && !$audio){
			$audio_file = get_post_meta( $id, 'enclosure', true );
			if( $audio_file ) {
				$file = $audio_file;
				// Podctrac compatibility change
				$arr = explode("pts/redirect.mp3/", $file );
				if( count( $arr) > 1 ){
					$file = $arr[1];
				}
				// Podctrac end
				$arr = explode('.mp3', $file);
				if(count($arr) > 0){
					$file = $arr[0].'.mp3';
					// remove redirects
					$arr = explode('http', $file);
					if( count($arr) > 2) {
						$file = 'http'.urldecode($arr[2]);
					}
				}
			}
		}

		// SINCE 2020 03 26
		// powerpress compatibility
		// Find any field called enclosure something
		// For compatibility with PowerPress
		if(!isset( $file )){
			$all_metas = get_post_meta( $id ) ;
			$key = preg_grep('/enclosure/', array_keys($all_metas));
			if( $key ){
				$value = $all_metas[current( $key )];
				if( is_array($value) && count($value) > 0 ){
					$file_val = $value[0];
					$arr2= explode("\n", $file_val );
					if( count( $arr2) > 1 ){
						$file_val = $arr2[0]; // should do the trick
					}
					if (strpos($file_val, '.mp3') !== false) {
					    $file = $file_val;
					}
				}
			}
		}

		if(isset( $file )){
			$track_data = array(
				'img_id' 		=> $id,
				'title'			=> $tracktitle,
				'artist_name'	=> $artist,
				'album'			=> '',
				'buyurl'		=> $buylink,
				'icon'			=> 'download',
				'link'			=> $link,
				'price'			=>	'',
				'file'			=> $file,
			);
			echo qtmplayer_create_singletrack($track_data);
		}
		$html = ob_get_clean();

		/**
		 * Display the tracklist below the player
		 * @var array
		 */
		$atts = array(
			'id' => $id ,
			'title_classes'	=> false,
			'classes' => 'qtmplayer-tracklist__autogenerated qtmplayer-tracklist__after', // additional container classes
			'print' => false // include the echo function
		);
		$html .= qtmplayer_tracklist( $atts );
	}
    return $html;
}
add_filter( 'wp_audio_shortcode_override', 'qtmplayer_audio_shortcode', 10, 2 );